#!/bin/bash

# shellcheck source=meta-facebook/recipes-fb/obmc_functions/files/fb-common-functions
source /usr/libexec/fb-common-functions

e1s_pwr_init() {
  e1s_0_prsnt=$(get_gpio E1S_0_PRSNT_N)
  if [[ "$e1s_0_prsnt" = "0" ]]; then
    set_gpio P12V_E1S_EN_0 1
  else
    set_gpio P12V_E1S_EN_0 0
  fi

  e1s_1_prsnt=$(get_gpio E1S_1_PRSNT_N)
  if [[ "$e1s_1_prsnt" = "0" ]]; then
    set_gpio P12V_E1S_EN_1 1
  else
    set_gpio P12V_E1S_EN_1 0
  fi
}

e1s_pwr_init

exit 0
